server:
  port: 8081

spring:
  #####################
  # 数据源相关配置配置
  ####################
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Mysql8.0