server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Mysql8.0
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
