spring:
  profiles:
    active: dev
  jpa:
    hibernate:
#      ddl-auto: create-drop
    #自动生成数据表
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

#    active: prod


# 指定api 是所有controller的根包
missyou:
  api-package: com.o0u0o.missyou.api

# 微信相关配置
wx:
  appid: wxd86e4c273a50faa8
  appsecret: 808ea4c46faa5eac8ea29ad67e6d0407
  code2session-url: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code

