spring:
  profiles:
    active: dev
  jpa:
    hibernate:
#      ddl-auto: create-drop
    #自动生成数据表
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

#    active: prod


# 指定api 是所有controller的根包
missyou:
  api-package: com.o0u0o.missyou.api

